### ISSUE TITLE
Not longer working

### ISSUE THREAD

**Issue by jantonioavalos** [koole/gatsby-plugin-hotjar-tracking#21]
I had to force: **includeInDevelopment: true** so it could be written and read by the hotjar validator. Actually code wasn't appearing using inspector until y put true.

Is there another way to get this work? In this workaround I did I need to put false each time I'm developing and return it to true when I push changes.

Thanks in advance for your answer. Maybe I'm doing something wrong or version need updates.

**Comment by koole** [comment]
Are you sure you're building your website for production (`gatsby build`) when you push changes? This library checks for `NODE_ENV=production` to see if it's not in development mode, which should be set by Gatsby when you run `gatsby build`.

**Comment by jantonioavalos** [comment]
Thanks for replying. It's working now. Maybe there was something slow from the server side.
